FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de dépendances d'abord (optimisation du cache Docker)
COPY package*.json ./

RUN npm install

# Copier le reste du code
COPY . .

EXPOSE 3000


CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]